services:
  mongo:
    image: mongo:8.0
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo-data:/data/db



  user-service:
    build:
      context: ./services
      dockerfile: user-service/Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/ecommerce?authSource=admin
      - JWT_SECRET=change_this_secret
    depends_on:
      - mongo

  product-service:
    build:
      context: ./services
      dockerfile: product-service/Dockerfile
    container_name: product-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/ecommerce?authSource=admin
    depends_on:
      - mongo

  cart-service:
    build:
      context: ./services
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/ecommerce?authSource=admin
    depends_on:
      - mongo

  order-service:
    build:
      context: ./services
      dockerfile: order-service/Dockerfile
    container_name: order-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/ecommerce?authSource=admin
      - CART_SERVICE_URL=http://cart-service:3003
    depends_on:
      - mongo
      - cart-service

  payment-service:
    build:
      context: ./services
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/ecommerce?authSource=admin
      - ORDER_SERVICE_URL=http://order-service:3004
    depends_on:
      - mongo
      - order-service

volumes:
  mongo-data:
